package com.intifix.modules.services.service.impl;

import com.intifix.modules.services.dto.request.CrearCotizacionRequest;
import com.intifix.modules.services.dto.request.ResponderCotizacionRequest;
import com.intifix.modules.services.dto.response.CotizacionResponse;
import com.intifix.modules.services.entity.Cotizacion;
import com.intifix.modules.services.entity.Servicio;
import com.intifix.modules.services.enums.EstadoCotizacion;
import com.intifix.modules.services.enums.EstadoServicio;
import com.intifix.modules.services.event.CotizacionAceptadaEvent;
import com.intifix.modules.services.exception.*;
import com.intifix.modules.services.gateway.TechnicianGateway;
import com.intifix.modules.services.gateway.UserGateway;
import com.intifix.modules.services.mapper.CotizacionMapper;
import com.intifix.modules.services.repository.CotizacionRepository;
import com.intifix.modules.services.repository.ServicioRepository;
import com.intifix.modules.services.service.CotizacionService;
import com.intifix.modules.audit.aspect.Auditable;
import com.intifix.modules.audit.entity.AuditAction;
import com.intifix.modules.audit.entity.AuditModule;
import com.intifix.shared.security.SecurityUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.intifix.modules.services.enums.TipoFecha;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.temporal.ChronoUnit;
import java.util.List;
import java.util.UUID;

/**
 * Service implementation for Cotizacion operations.
 * 
 * @author INTIFIX Architecture Team
 * @version 1.0
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class CotizacionServiceImpl implements CotizacionService {

    private static final String MSG_COTIZACION_NO_ENCONTRADA = "Cotización no encontrada: {}";

    private final CotizacionRepository cotizacionRepository;
    private final ServicioRepository servicioRepository;
    private final CotizacionMapper cotizacionMapper;
    private final TechnicianGateway technicianGateway;
    private final UserGateway userGateway;
    private final ApplicationEventPublisher eventPublisher;

    @Override
    @Transactional
    @Auditable(module = AuditModule.SERVICES, action = AuditAction.CREAR, resourceType = "Cotizacion")
    public CotizacionResponse crearCotizacion(CrearCotizacionRequest request) {
        UUID idUsuarioTecnico = SecurityUtils.currentUserId();
        log.info("Creando cotización para servicio: {} por técnico autenticado: {}", 
            request.getIdServicio(), idUsuarioTecnico);

        Servicio servicio = servicioRepository.findById(request.getIdServicio())
            .orElseThrow(() -> {
                log.warn("Servicio no encontrado: {}", request.getIdServicio());
                return ServicioNoEncontradoException.byId(request.getIdServicio());
            });

        if (servicio.getEstado() == EstadoServicio.FINALIZADO) {
            log.warn("Intento de cotizar servicio finalizado: {}", request.getIdServicio());
            throw ServicioFinalizadoException.cannotQuote(request.getIdServicio());
        }

        if (!userGateway.isUserActive(servicio.getIdCliente())) {
            log.warn("Intento de cotizar servicio de cliente inactivo: {}", request.getIdServicio());
            throw ClienteNoActivoException.forServicio(request.getIdServicio());
        }

        if (!technicianGateway.existsTechnician(idUsuarioTecnico)) {
            log.warn("Técnico no encontrado: {}", idUsuarioTecnico);
            throw TecnicoNoEncontradoException.byId(idUsuarioTecnico);
        }

        if (!technicianGateway.isApproved(idUsuarioTecnico)) {
            log.warn("Técnico no aprobado: {}", idUsuarioTecnico);
            throw TecnicoNoAprobadoException.byId(idUsuarioTecnico);
        }

        if (!technicianGateway.isAvailable(idUsuarioTecnico)) {
            log.warn("Técnico no disponible: {}", idUsuarioTecnico);
            throw TecnicoNoDisponibleException.byId(idUsuarioTecnico);
        }

        ZonedDateTime ahora = ZonedDateTime.now(ZoneId.systemDefault());
        validarFechaPropuesta(request, servicio, ahora);

        Cotizacion cotizacion = cotizacionMapper.toEntity(request);
        cotizacion.setIdUsuarioTecnico(idUsuarioTecnico);
        cotizacion.setEstado(EstadoCotizacion.PENDIENTE);
        // UUID and fechaEnvio will be generated by database via Persistable<UUID> and DEFAULT CURRENT_TIMESTAMP
        // fechaExpiracion is business logic (48 hours from now), set in entity @PrePersist

        Cotizacion guardada = cotizacionRepository.save(cotizacion);

        if (servicio.getEstado() == EstadoServicio.PENDIENTE) {
            servicio.setEstado(EstadoServicio.COTIZANDO);
            servicioRepository.save(servicio);
        }

        log.info("Cotización creada exitosamente: {}", guardada.getIdCotizacion());
        return cotizacionMapper.toResponse(guardada);
    }

    @Override
    @Transactional
    public CotizacionResponse responderCotizacion(UUID idCotizacion, ResponderCotizacionRequest request) {
        log.info("Respondiendo cotización: {} con estado: {}", idCotizacion, request.getEstado());

        Cotizacion cotizacion = cotizacionRepository.findById(idCotizacion)
            .orElseThrow(() -> {
                log.warn(MSG_COTIZACION_NO_ENCONTRADA, idCotizacion);
                return CotizacionNoEncontradaException.byId(idCotizacion);
            });

        if (cotizacion.getEstado() != EstadoCotizacion.PENDIENTE) {
            log.warn("Cotización ya respondida: {}", idCotizacion);
            throw CotizacionNoModificableException.alreadyResponded(idCotizacion);
        }

        cotizacion.setEstado(request.getEstado());
        cotizacion.setFechaRespuesta(ZonedDateTime.now(ZoneId.systemDefault()));

        if (request.getEstado() == EstadoCotizacion.RECHAZADA) {
            cotizacion.setMotivoRechazo(request.getMotivo());
        }

        Cotizacion actualizada = cotizacionRepository.save(cotizacion);

        if (request.getEstado() == EstadoCotizacion.ACEPTADA) {
            Servicio servicio = servicioRepository.findById(cotizacion.getIdServicio())
                .orElseThrow(() -> ServicioNoEncontradoException.byId(cotizacion.getIdServicio()));

            eventPublisher.publishEvent(new CotizacionAceptadaEvent(
                actualizada.getIdCotizacion(),
                actualizada.getIdServicio(),
                actualizada.getIdUsuarioTecnico(),
                servicio.getIdCliente(),
                actualizada.getPrecio(),
                actualizada.getTiempoEstimado(),
                actualizada.getFechaRespuesta()
            ));
        }

        log.info("Cotización respondida exitosamente: {}", actualizada.getIdCotizacion());
        return cotizacionMapper.toResponse(actualizada);
    }

    @Override
    @Transactional
    public void eliminarCotizacion(UUID idCotizacion) {
        log.info("Eliminando cotización: {}", idCotizacion);

        Cotizacion cotizacion = cotizacionRepository.findById(idCotizacion)
            .orElseThrow(() -> {
                log.warn(MSG_COTIZACION_NO_ENCONTRADA, idCotizacion);
                return CotizacionNoEncontradaException.byId(idCotizacion);
            });

        if (cotizacion.getEstado() == EstadoCotizacion.ACEPTADA) {
            log.warn("Intento de eliminar cotización aceptada: {}", idCotizacion);
            throw CotizacionNoModificableException.accepted(idCotizacion);
        }

        cotizacionRepository.delete(cotizacion);
        log.info("Cotización eliminada exitosamente: {}", idCotizacion);
    }

    @Override
    @Transactional(readOnly = true)
    public CotizacionResponse obtenerCotizacionPorId(UUID idCotizacion) {
        log.debug("Obteniendo cotización por ID: {}", idCotizacion);

        Cotizacion cotizacion = cotizacionRepository.findById(idCotizacion)
            .orElseThrow(() -> {
                log.warn(MSG_COTIZACION_NO_ENCONTRADA, idCotizacion);
                return CotizacionNoEncontradaException.byId(idCotizacion);
            });

        return cotizacionMapper.toResponse(cotizacion);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<CotizacionResponse> obtenerCotizacionesPorServicio(UUID idServicio, Pageable pageable) {
        log.debug("Obteniendo cotizaciones por servicio: {}", idServicio);
        Page<Cotizacion> cotizaciones = cotizacionRepository.findByIdServicio(idServicio, pageable);
        return cotizaciones.map(cotizacionMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<CotizacionResponse> obtenerCotizacionesPorTecnico(UUID idUsuarioTecnico, Pageable pageable) {
        log.debug("Obteniendo cotizaciones por técnico: {}", idUsuarioTecnico);
        Page<Cotizacion> cotizaciones = cotizacionRepository.findByIdUsuarioTecnico(idUsuarioTecnico, pageable);
        return cotizaciones.map(cotizacionMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<CotizacionResponse> obtenerCotizacionesPendientesPorServicio(UUID idServicio, Pageable pageable) {
        log.debug("Obteniendo cotizaciones pendientes por servicio: {}", idServicio);
        Page<Cotizacion> cotizaciones = cotizacionRepository.findPendientesByServicio(idServicio, ZonedDateTime.now(ZoneId.systemDefault()), pageable);
        return cotizaciones.map(cotizacionMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<CotizacionResponse> obtenerCotizacionesPorServicioOrdenadasPorPrecio(UUID idServicio, boolean ascendente, Pageable pageable) {
        log.debug("Obteniendo cotizaciones por servicio ordenadas por precio: {}", idServicio);
        Page<Cotizacion> cotizaciones = ascendente 
            ? cotizacionRepository.findByIdServicioOrderByPrecioAsc(idServicio, pageable)
            : cotizacionRepository.findByIdServicioOrderByPrecioDesc(idServicio, pageable);
        return cotizaciones.map(cotizacionMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public long contarCotizacionesPorServicio(UUID idServicio) {
        log.debug("Contando cotizaciones por servicio: {}", idServicio);
        return cotizacionRepository.countByIdServicio(idServicio);
    }

    @Override
    @Transactional(readOnly = true)
    public long contarCotizacionesPorTecnico(UUID idUsuarioTecnico) {
        log.debug("Contando cotizaciones por técnico: {}", idUsuarioTecnico);
        return cotizacionRepository.countByIdUsuarioTecnico(idUsuarioTecnico);
    }

    @Override
    @Transactional(readOnly = true)
    public boolean existeCotizacion(UUID idCotizacion) {
        return cotizacionRepository.existsById(idCotizacion);
    }

    @Override
    @Transactional
    public void expirarCotizacionesVencidas() {
        log.info("Expirando cotizaciones vencidas");
        List<Cotizacion> vencidas = cotizacionRepository.findExpired(ZonedDateTime.now(ZoneId.systemDefault()));

        for (Cotizacion cotizacion : vencidas) {
            cotizacion.setEstado(EstadoCotizacion.EXPIRADA);
            cotizacionRepository.save(cotizacion);
        }

        log.info("Cotizaciones expiradas: {}", vencidas.size());
    }

    private void validarFechaPropuesta(CrearCotizacionRequest request, Servicio servicio, ZonedDateTime ahora) {
        TipoFecha tipoFecha = servicio.getTipoFecha() != null ? servicio.getTipoFecha() : TipoFecha.EXACTA;
        switch (tipoFecha) {
            case URGENTE -> validarFechaUrgente(request, ahora);
            case RANGO -> validarFechaRango(request, servicio, ahora);
            case EXACTA -> { /* fecha fijada por el cliente; no se requiere propuesta */ }
        }
    }

    private void validarFechaUrgente(CrearCotizacionRequest request, ZonedDateTime ahora) {
        if (request.getFechaPropuesta() == null)
            throw new IllegalArgumentException("Debes proponer una hora: hoy o a más tardar mañana.");
        if (!request.getFechaPropuesta().isAfter(ahora))
            throw new IllegalArgumentException("La fecha propuesta debe ser futura.");
        ZonedDateTime limiteUrgente = ahora.plusDays(2).truncatedTo(ChronoUnit.DAYS);
        if (!request.getFechaPropuesta().isBefore(limiteUrgente))
            throw new IllegalArgumentException("Para servicios urgentes solo puedes proponer hoy o mañana.");
    }

    private void validarFechaRango(CrearCotizacionRequest request, Servicio servicio, ZonedDateTime ahora) {
        if (request.getFechaPropuesta() == null)
            throw new IllegalArgumentException("Debes proponer una fecha y hora dentro del rango solicitado.");
        if (!request.getFechaPropuesta().isAfter(ahora))
            throw new IllegalArgumentException("La fecha propuesta debe ser futura.");
        ZonedDateTime finRango = servicio.getFechaFinRango().plusDays(1).truncatedTo(ChronoUnit.DAYS);
        if (request.getFechaPropuesta().isBefore(servicio.getFechaInicioRango()) ||
            !request.getFechaPropuesta().isBefore(finRango))
            throw new IllegalArgumentException("La fecha propuesta debe estar dentro del rango indicado por el cliente.");
    }
}
