package com.intifix.modules.services.service.impl;

import com.intifix.modules.services.dto.request.CrearReporteRequest;
import com.intifix.modules.services.dto.response.ReporteResponse;
import com.intifix.modules.services.entity.Reporte;
import com.intifix.modules.services.enums.EstadoReporte;
import com.intifix.modules.services.exception.ReporteNoEncontradoException;
import com.intifix.modules.services.exception.ReporteNoModificableException;
import com.intifix.modules.services.mapper.ReporteMapper;
import com.intifix.modules.services.repository.ReporteRepository;
import com.intifix.modules.services.service.ReporteService;
import com.intifix.shared.security.SecurityUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.UUID;

/**
 * Service implementation for Reporte operations.
 * 
 * @author INTIFIX Architecture Team
 * @version 1.0
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ReporteServiceImpl implements ReporteService {

    private static final String MSG_REPORTE_NO_ENCONTRADO = "Reporte no encontrado: {}";

    private final ReporteRepository reporteRepository;
    private final ReporteMapper reporteMapper;

    @Override
    @Transactional
    public ReporteResponse crearReporte(CrearReporteRequest request) {
        UUID idReportante = SecurityUtils.currentUserId();
        log.info("Creando reporte por usuario autenticado: {}", idReportante);

        Reporte reporte = reporteMapper.toEntity(request);
        reporte.setIdReportante(idReportante);
        reporte.setEstado(EstadoReporte.PENDIENTE);
        // UUID and fechaReporte will be generated by database via Persistable<UUID> and DEFAULT CURRENT_TIMESTAMP

        if (request.getPrioridad() == null) {
            reporte.setPrioridad("MEDIA");
        }

        Reporte guardado = reporteRepository.save(reporte);

        log.info("Reporte creado exitosamente: {}", guardado.getIdReporte());
        return reporteMapper.toResponse(guardado);
    }

    @Override
    @Transactional
    public ReporteResponse actualizarReporte(UUID idReporte, String resolucion, String accionTomada) {
        log.info("Actualizando reporte: {}", idReporte);

        Reporte reporte = reporteRepository.findById(idReporte)
            .orElseThrow(() -> {
                log.warn(MSG_REPORTE_NO_ENCONTRADO, idReporte);
                return ReporteNoEncontradoException.byId(idReporte);
            });

        reporte.setResolucion(resolucion);
        reporte.setAccionTomada(accionTomada);
        reporte.setEstado(EstadoReporte.RESUELTO);
        reporte.setFechaResolucion(java.time.ZonedDateTime.now());

        Reporte actualizado = reporteRepository.save(reporte);

        log.info("Reporte actualizado exitosamente: {}", actualizado.getIdReporte());
        return reporteMapper.toResponse(actualizado);
    }

    @Override
    @Transactional
    public void eliminarReporte(UUID idReporte) {
        log.info("Eliminando reporte: {}", idReporte);

        Reporte reporte = reporteRepository.findById(idReporte)
            .orElseThrow(() -> {
                log.warn(MSG_REPORTE_NO_ENCONTRADO, idReporte);
                return ReporteNoEncontradoException.byId(idReporte);
            });

        if (reporte.getEstado() == EstadoReporte.EN_REVISION) {
            log.warn("Intento de eliminar reporte en investigación: {}", idReporte);
            throw ReporteNoModificableException.underInvestigation(idReporte);
        }

        reporteRepository.delete(reporte);
        log.info("Reporte eliminado exitosamente: {}", idReporte);
    }

    @Override
    @Transactional(readOnly = true)
    public ReporteResponse obtenerReportePorId(UUID idReporte) {
        log.debug("Obteniendo reporte por ID: {}", idReporte);

        Reporte reporte = reporteRepository.findById(idReporte)
            .orElseThrow(() -> {
                log.warn(MSG_REPORTE_NO_ENCONTRADO, idReporte);
                return ReporteNoEncontradoException.byId(idReporte);
            });

        return reporteMapper.toResponse(reporte);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ReporteResponse> obtenerReportesPorServicio(UUID idServicio, Pageable pageable) {
        log.debug("Obteniendo reportes por servicio: {}", idServicio);
        Page<Reporte> reportes = reporteRepository.findByIdServicio(idServicio, pageable);
        return reportes.map(reporteMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ReporteResponse> obtenerReportesPorReportante(UUID idReportante, Pageable pageable) {
        log.debug("Obteniendo reportes por reportante: {}", idReportante);
        Page<Reporte> reportes = reporteRepository.findByIdReportante(idReportante, pageable);
        return reportes.map(reporteMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ReporteResponse> obtenerReportesPorReportado(UUID idReportado, Pageable pageable) {
        log.debug("Obteniendo reportes por reportado: {}", idReportado);
        Page<Reporte> reportes = reporteRepository.findByIdReportado(idReportado, pageable);
        return reportes.map(reporteMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ReporteResponse> obtenerReportesPorEstado(EstadoReporte estado, Pageable pageable) {
        log.debug("Obteniendo reportes por estado: {}", estado);
        Page<Reporte> reportes = reporteRepository.findByEstado(estado, pageable);
        return reportes.map(reporteMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ReporteResponse> obtenerReportesPorTipo(String tipoReporte, Pageable pageable) {
        log.debug("Obteniendo reportes por tipo: {}", tipoReporte);
        Page<Reporte> reportes = reporteRepository.findByTipoReporte(tipoReporte, pageable);
        return reportes.map(reporteMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ReporteResponse> obtenerReportesPendientes(Pageable pageable) {
        log.debug("Obteniendo reportes pendientes");
        Page<Reporte> reportes = reporteRepository.findPendientesOrderByFechaReporteAsc(pageable);
        return reportes.map(reporteMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ReporteResponse> obtenerReportesPendientesAltaPrioridad(Pageable pageable) {
        log.debug("Obteniendo reportes pendientes de alta prioridad");
        Page<Reporte> reportes = reporteRepository.findPendientesAltaPrioridad(pageable);
        return reportes.map(reporteMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public long contarReportesPorEstado(EstadoReporte estado) {
        log.debug("Contando reportes por estado: {}", estado);
        return reporteRepository.countByEstado(estado);
    }

    @Override
    @Transactional(readOnly = true)
    public long contarReportesPorReportante(UUID idReportante) {
        log.debug("Contando reportes por reportante: {}", idReportante);
        return reporteRepository.countByIdReportante(idReportante);
    }

    @Override
    @Transactional(readOnly = true)
    public long contarReportesPorReportado(UUID idReportado) {
        log.debug("Contando reportes por reportado: {}", idReportado);
        return reporteRepository.countByIdReportado(idReportado);
    }

    @Override
    @Transactional(readOnly = true)
    public boolean existeReporte(UUID idReporte) {
        return reporteRepository.existsById(idReporte);
    }
}
