package com.intifix.modules.services.service.impl;

import com.intifix.modules.services.dto.request.ActualizarServicioRequest;
import com.intifix.modules.services.dto.request.CambiarEstadoServicioRequest;
import com.intifix.modules.services.dto.request.CrearServicioRequest;
import com.intifix.modules.services.dto.response.ServicioDetalleResponse;
import com.intifix.modules.services.dto.response.ServicioResponse;
import com.intifix.modules.services.entity.HistorialServicio;
import com.intifix.modules.services.entity.Servicio;
import com.intifix.modules.services.enums.EstadoServicio;
import com.intifix.modules.services.event.ServicioCreadoEvent;
import com.intifix.modules.audit.event.ServiceCreatedEvent;
import com.intifix.modules.audit.event.ServiceCancelledEvent;
import com.intifix.modules.services.exception.*;
import com.intifix.modules.services.gateway.GeolocationGateway;
import com.intifix.modules.services.gateway.UserGateway;
import com.intifix.modules.services.mapper.ServicioMapper;
import com.intifix.modules.services.repository.HistorialServicioRepository;
import com.intifix.modules.services.repository.ServicioRepository;
import com.intifix.modules.services.service.ServicioService;
import com.intifix.shared.security.SecurityUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.context.ApplicationEventPublisher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.UUID;

/**
 * Service implementation for Servicio operations.
 * 
 * @author INTIFIX Architecture Team
 * @version 1.0
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class ServicioServiceImpl implements ServicioService {

    private static final String ROL_ADMIN = "ADMIN";
    private static final String ROL_TECNICO = "TECNICO";

    private final ServicioRepository servicioRepository;
    private final HistorialServicioRepository historialServicioRepository;
    private final ServicioMapper servicioMapper;
    private final UserGateway userGateway;
    private final GeolocationGateway geolocationGateway;
    private final ApplicationEventPublisher eventPublisher;

    @Override
    @Transactional
    public ServicioResponse crearServicio(CrearServicioRequest request) {
        UUID idCliente = SecurityUtils.currentUserId();
        log.info("Creando servicio para cliente autenticado: {}", idCliente);

        if (!userGateway.existsClient(idCliente)) {
            log.warn("Cliente no encontrado: {}", idCliente);
            throw ClienteNoEncontradoException.byId(idCliente);
        }

        if (!geolocationGateway.existsLocation(request.getIdUbicacion())) {
            log.warn("Ubicación no encontrada: {}", request.getIdUbicacion());
            throw UbicacionNoEncontradaException.byId(request.getIdUbicacion());
        }

        Servicio servicio = servicioMapper.toEntity(request);
        servicio.setIdCliente(idCliente);
        servicio.setEstado(EstadoServicio.PENDIENTE);
        // UUID will be generated by database via Persistable<UUID>

        Servicio guardado = servicioRepository.save(servicio);
        
        registrarHistorial(guardado.getIdServicio(), null, EstadoServicio.PENDIENTE, "Servicio creado", idCliente);
        
        eventPublisher.publishEvent(new ServicioCreadoEvent(
            guardado.getIdServicio(),
            guardado.getIdCliente(),
            guardado.getIdUbicacion(),
            guardado.getTitulo(),
            guardado.getFechaCreacion()
        ));

        // Auditoría desacoplada del alta de servicio.
        eventPublisher.publishEvent(new ServiceCreatedEvent(
            guardado.getIdServicio(),
            guardado.getIdCliente()
        ));

        log.info("Servicio creado exitosamente: {}", guardado.getIdServicio());
        return servicioMapper.toResponse(guardado);
    }

    @Override
    @Transactional
    public ServicioResponse actualizarServicio(UUID idServicio, ActualizarServicioRequest request) {
        log.info("Actualizando servicio: {}", idServicio);

        Servicio servicio = servicioRepository.findById(idServicio)
            .orElseThrow(() -> {
                log.warn("Servicio no encontrado: {}", idServicio);
                return ServicioNoEncontradoException.byId(idServicio);
            });

        verificarPropiedadOAdmin(servicio);

        if (servicio.getEstado() == EstadoServicio.FINALIZADO) {
            log.warn("Intento de actualizar servicio finalizado: {}", idServicio);
            throw ServicioNoModificableException.finalized(idServicio);
        }

        servicioMapper.updateEntityFromDto(request, servicio);
        Servicio actualizado = servicioRepository.save(servicio);

        log.info("Servicio actualizado exitosamente: {}", actualizado.getIdServicio());
        return servicioMapper.toResponse(actualizado);
    }

    @Override
    @Transactional
    public ServicioResponse cambiarEstadoServicio(UUID idServicio, CambiarEstadoServicioRequest request) {
        log.info("Cambiando estado del servicio: {} a {}", idServicio, request.getEstado());

        Servicio servicio = servicioRepository.findById(idServicio)
            .orElseThrow(() -> {
                log.warn("Servicio no encontrado: {}", idServicio);
                return ServicioNoEncontradoException.byId(idServicio);
            });

        verificarPropiedadOAdmin(servicio);

        EstadoServicio estadoAnterior = servicio.getEstado();
        EstadoServicio estadoNuevo = request.getEstado();

        if (estadoAnterior == EstadoServicio.FINALIZADO) {
            log.warn("Intento de cambiar estado de servicio finalizado: {}", idServicio);
            throw ServicioNoModificableException.finalized(idServicio);
        }

        validarTransicion(idServicio, estadoAnterior, estadoNuevo);

        servicio.setEstado(estadoNuevo);

        if (estadoNuevo == EstadoServicio.FINALIZADO) {
            servicio.setFechaFinalizacion(java.time.ZonedDateTime.now());
        }

        Servicio actualizado = servicioRepository.save(servicio);

        registrarHistorial(
            actualizado.getIdServicio(),
            estadoAnterior,
            estadoNuevo,
            request.getComentario(),
            SecurityUtils.currentUserId()
        );

        if (estadoNuevo == EstadoServicio.CANCELADO) {
            eventPublisher.publishEvent(new ServiceCancelledEvent(
                actualizado.getIdServicio(),
                SecurityUtils.currentUserId(),
                request.getComentario()
            ));
        }

        log.info("Estado del servicio cambiado exitosamente: {} de {} a {}",
            idServicio, estadoAnterior, estadoNuevo);
        return servicioMapper.toResponse(actualizado);
    }

    @Override
    @Transactional
    public void eliminarServicio(UUID idServicio) {
        log.info("Eliminando servicio: {}", idServicio);

        Servicio servicio = servicioRepository.findById(idServicio)
            .orElseThrow(() -> {
                log.warn("Servicio no encontrado: {}", idServicio);
                return ServicioNoEncontradoException.byId(idServicio);
            });

        verificarPropiedadOAdmin(servicio);

        if (servicio.getEstado() != EstadoServicio.PENDIENTE) {
            log.warn("Intento de eliminar servicio no pendiente: {}", idServicio);
            throw ServicioNoEliminableException.notPending(idServicio);
        }

        servicioRepository.delete(servicio);
        log.info("Servicio eliminado exitosamente: {}", idServicio);
    }

    @Override
    @Transactional(readOnly = true)
    public ServicioResponse obtenerServicioPorId(UUID idServicio) {
        log.debug("Obteniendo servicio por ID: {}", idServicio);

        Servicio servicio = servicioRepository.findById(idServicio)
            .orElseThrow(() -> {
                log.warn("Servicio no encontrado: {}", idServicio);
                return ServicioNoEncontradoException.byId(idServicio);
            });

        verificarAccesoLectura(servicio);

        return servicioMapper.toResponse(servicio);
    }

    @Override
    @Transactional(readOnly = true)
    public ServicioDetalleResponse obtenerDetalleServicioPorId(UUID idServicio) {
        log.debug("Obteniendo detalle de servicio por ID: {}", idServicio);

        Servicio servicio = servicioRepository.findById(idServicio)
            .orElseThrow(() -> {
                log.warn("Servicio no encontrado: {}", idServicio);
                return ServicioNoEncontradoException.byId(idServicio);
            });

        verificarAccesoLectura(servicio);

        ServicioDetalleResponse.ServicioDetalleResponseBuilder builder = ServicioDetalleResponse.builder()
            .idServicio(servicio.getIdServicio())
            .idCliente(servicio.getIdCliente())
            .idUbicacion(servicio.getIdUbicacion())
            .titulo(servicio.getTitulo())
            .descripcion(servicio.getDescripcion())
            .modalidad(servicio.getModalidad())
            .prioridad(servicio.getPrioridad())
            .estado(servicio.getEstado())
            .presupuestoMaximo(servicio.getPresupuestoMaximo())
            .fechaProgramada(servicio.getFechaProgramada())
            .fechaCreacion(servicio.getFechaCreacion())
            .fechaActualizacion(servicio.getFechaActualizacion())
            .fechaFinalizacion(servicio.getFechaFinalizacion())
            .motivoCancelacion(servicio.getMotivoCancelacion());

        return builder.build();
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ServicioResponse> obtenerServiciosPorCliente(UUID idCliente, Pageable pageable) {
        log.debug("Obteniendo servicios por cliente: {}", idCliente);
        Page<Servicio> servicios = servicioRepository.findByIdCliente(idCliente, pageable);
        return servicios.map(servicioMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ServicioResponse> obtenerServiciosPorUbicacion(UUID idUbicacion, Pageable pageable) {
        log.debug("Obteniendo servicios por ubicación: {}", idUbicacion);
        Page<Servicio> servicios = servicioRepository.findByIdUbicacion(idUbicacion, pageable);
        return servicios.map(servicioMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ServicioResponse> obtenerServiciosPorEstado(EstadoServicio estado, Pageable pageable) {
        log.debug("Obteniendo servicios por estado: {}", estado);
        Page<Servicio> servicios = servicioRepository.findByEstado(estado, pageable);
        return servicios.map(servicioMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ServicioResponse> obtenerServiciosDisponibles(Pageable pageable) {
        log.debug("Obteniendo servicios disponibles (marketplace)");
        Page<Servicio> servicios = servicioRepository.findByEstadoIn(
            List.of(EstadoServicio.PENDIENTE, EstadoServicio.COTIZANDO), pageable);
        return servicios.map(servicioMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public Page<ServicioResponse> buscarServiciosPorTitulo(String titulo, Pageable pageable) {
        log.debug("Buscando servicios por título: {}", titulo);
        Page<Servicio> servicios = servicioRepository.buscarPorTitulo(titulo, pageable);
        return servicios.map(servicioMapper::toResponse);
    }

    @Override
    @Transactional(readOnly = true)
    public long contarServiciosPorCliente(UUID idCliente) {
        log.debug("Contando servicios por cliente: {}", idCliente);
        return servicioRepository.countByIdCliente(idCliente);
    }

    @Override
    @Transactional(readOnly = true)
    public long contarServiciosPorEstado(EstadoServicio estado) {
        log.debug("Contando servicios por estado: {}", estado);
        return servicioRepository.countByEstado(estado);
    }

    @Override
    @Transactional(readOnly = true)
    public boolean existeServicio(UUID idServicio) {
        return servicioRepository.existsById(idServicio);
    }

    /**
     * Autoriza operaciones de mutación: solo ADMIN o el cliente dueño del servicio.
     * Lanza {@link AccessDeniedException} (403) en caso contrario.
     */
    private void verificarPropiedadOAdmin(Servicio servicio) {
        if (SecurityUtils.tieneRol(ROL_ADMIN)) {
            return;
        }
        if (!SecurityUtils.esPropietario(servicio.getIdCliente())) {
            log.warn("Acceso denegado al servicio {} para usuario {}",
                servicio.getIdServicio(), SecurityUtils.currentUserId());
            throw new AccessDeniedException("No tiene permiso sobre este servicio");
        }
    }

    /**
     * Autoriza lectura por id: ADMIN y TECNICO ven cualquier servicio (marketplace);
     * un CLIENTE solo puede leer los suyos.
     */
    private void verificarAccesoLectura(Servicio servicio) {
        if (SecurityUtils.tieneRol(ROL_ADMIN) || SecurityUtils.tieneRol(ROL_TECNICO)) {
            return;
        }
        if (!SecurityUtils.esPropietario(servicio.getIdCliente())) {
            log.warn("Lectura denegada del servicio {} para usuario {}",
                servicio.getIdServicio(), SecurityUtils.currentUserId());
            throw new AccessDeniedException("No tiene permiso sobre este servicio");
        }
    }

    /**
     * Máquina de estados. ADMIN puede ejecutar cualquier transición (la salida
     * desde FINALIZADO ya está bloqueada antes). Un CLIENTE dueño solo puede
     * cancelar, y únicamente desde estados tempranos del ciclo de vida.
     */
    private void validarTransicion(UUID idServicio, EstadoServicio desde, EstadoServicio hacia) {
        if (SecurityUtils.tieneRol(ROL_ADMIN)) {
            return;
        }
        boolean clienteCancelaPermitido = hacia == EstadoServicio.CANCELADO
            && (desde == EstadoServicio.PENDIENTE
                || desde == EstadoServicio.COTIZANDO
                || desde == EstadoServicio.ASIGNADO);
        if (!clienteCancelaPermitido) {
            log.warn("Transición no permitida para CLIENTE en servicio {}: {} -> {}",
                idServicio, desde, hacia);
            throw ServicioNoModificableException.transicionInvalida(idServicio, desde, hacia);
        }
    }

    private void registrarHistorial(UUID idServicio, EstadoServicio estadoAnterior,
                                   EstadoServicio estadoNuevo, String comentario, UUID cambiadoPor) {
        HistorialServicio historial = HistorialServicio.builder()
            .idHistorial(UUID.randomUUID())
            .idServicio(idServicio)
            .estadoAnterior(estadoAnterior)
            .estadoNuevo(estadoNuevo)
            .comentario(comentario)
            .cambiadoPor(cambiadoPor)
            .fechaCambio(java.time.ZonedDateTime.now())
            .build();
        
        historialServicioRepository.save(historial);
    }
}
